### ISSUE TITLE
fig:means-date & fig:means-age-update not generated, but referenced

### ISSUE THREAD

**Issue by katrinleinweber** [zambujo/snsf-peerreview#5]
Thanks for publishing this notebook! I'm considering using it in an intro talk to literal programming :-)

Small issue: There are 2 `figure ??` occurrences in the notebook, probably because of https://github.com/zambujo/snsf-peerreview/commit/55092e1f7fc0d093aa42ae39117b725eb741efdf#diff-a2342216b8cfea004a495195a2a0ec07R477 & https://github.com/zambujo/snsf-peerreview/commit/6b689d69198e935fd66966d25b8fa2a99fca80f5#diff-a2342216b8cfea004a495195a2a0ec07R688.

**Comment by zambujo** [comment]
@katrinleinweber thanks for spotting this: will fix it

> `fig:means-date`is no longer in use after data anonymization

**Comment by katrinleinweber** [comment]
You're welcome :-)
